backend:
  name: github
  repo: codeblick/codestories
  branch: master

publish_mode: editorial_workflow

media_folder: "static/uploads"
public_folder: "uploads"

collections:
  - name: "posts"
    label: "Post"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Cover Image", name: "thumbnail", widget: "image"}
      - {label: "Publish Date", name: "timestamp", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
